quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Bloomberg Terminal": [0.8, 0.6]
    "Yahoo Finance": [0.7, 0.4]
    "Google Finance": [0.7, 0.4]
    "Finbox": [0.5, 0.5]
    "Gurufocus": [0.6, 0.6]
    "Intrinio": [0.4, 0.5]
    "Seeking Alpha": [0.6, 0.4]
    "Our Target Product": [0.5, 0.7]
